language: python
python:
    - "3.6"

before_install:
    - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update
    - sudo apt-get install libgeos-dev
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install scipy
    - pip install matplotlib
    - pip install -U pytest

script:
    - cd test
    - pytest
